### ISSUE TITLE
CI/CD plans

### ISSUE THREAD

**Issue by hammer** [refstudio/refstudio#10]
We'd like to get CI/CD set up quickly for this project. @sergioramos notes that for MacOS testing we'll need to sign our code, as noted in the Tauri docs: https://tauri.app/v1/guides/distribution/sign-macos.

@jonaskruckenberg @denjell-crabnebula any other tips for us on CI/CD for Tauri apps? Obviously there's the testing section in your docs but if there are any practical lessons you've learned that haven't made it into the docs yet we'd love to hear them! In particular we're concerned about testing on Windows since we don't have any Windows users. Any pro tips on how to build apps to make them maximally compatible across Mac and Windows?

**Comment by sergioramos** [comment]
On every Commit/PR:

<details>

<summary>Example</summary>

```yaml
name: Continuous Integration

on:
  push:
    branches:
      - master
      - main
  pull_request:
```

</details>



- [ ] Install dependencies and setup environment (with caches)

<details>

<summary>Example</summary>

```yml
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
        env:
          YARN_CHECKSUM_BEHAVIOR: update
          YARN_ENABLE_SCRIPTS: 0
```

</details>

- [ ] Lint commits

<details>

<summary>Example</summary>

```yml
  commitlint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
      - name: Commit Lint
        uses: wagoid/commitlint-github-action@v5.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

</details>

- [ ] Eslint

<details>

<summary>Example</summary>

```yml
  eslint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: ESLint
        run: yarn run lint
```

</details>

- [ ] Make sure dependencies are in sync (only makes sense in a monorepo )

<details>

<summary>Example</summary>

```yaml
  constraints:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: Constraints
        run: yarn constraints
```

</details>

- [ ] Test (with coverage report)

<details>

<summary>Example</summary>

```yml
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Test
        run: yarn run test --testLocationInResults --ci --json --outputFile="coverage.json"
        # this is not working well
      - name: Download Coverage Artifact
        uses: actions/download-artifact@v3.0.2
        continue-on-error: true
        with:
          name: coverage
          path: base-coverage.json
      - name: Fallback coverage report
        run: |
          [ -e "base-coverage.json" ] || cp coverage.json base-coverage.json
      - name: Jest coverage report
        if: github.event_name == 'pull_request'
        uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-file: coverage.json
          base-coverage-file: base-coverage.json
          skip-step: all
          annotations: none
          icons: ascii
      - name: Set base coverage report
        if: github.event_name != 'pull_request'
        run: cp coverage.json base-coverage.json
      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v3.1.2
        if: github.event_name != 'pull_request'
        with:
          name: coverage
          path: base-coverage.json
          retention-days: 90
```

</details>

- [ ] Release and build (https://tauri.app/v1/guides/distribution/sign-macos)

<details>

<summary>Example</summary>

```yaml
  release:
    needs: [eslint, commitlint, test, constraints]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Generate release token
      id: release_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.RELEASE_APP_ID }}
        private_key: ${{ secrets.RELEASE_PRIVATE_KEY }}
    - name: Get branch
      uses: rlespinasse/github-slug-action@4.0.0
    - name: Release
      uses: ridedott/release-me-action@v3.6.25
      if: ${{ env.GITHUB_REF_SLUG == 'master' }}
      env:
        GITHUB_TOKEN: ${{ steps.release_token.outputs.token }}
```

```yaml
name: Continuous Delivery

on:
  release:
    types: [created]

jobs:
  bundle-sources:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.5.1
      with:
        node-version: 'lts/*'
    - name: Install dependencies
      run: yarn install --immutable
    - name: Bundle
    - name: Upload artifacts
      uses: Shopify/upload-to-release@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: 
        path: 
        repo-token: ${{ secrets.GITHUB_TOKEN }}
```

</details>

**Comment by gjreda** [comment]
For Python:

- [ ] Setup Python
<summary>Example</summary>
<details>

```yaml
strategy:
  matrix:
    python-version: ["3.10", "3.11"]

steps:
  - uses: actions/checkout@v3
  - name: Set up Python ${{ matrix.python-version }}
    uses: actions/setup-python@v4
    with:
      python-version: ${{ matrix.python-version }}
```
</details>

- [ ] Install poetry and dependencies

Example below uses pip, can use this for poetry: https://github.com/snok/install-poetry
<summary>Example</summary>
<details>

```yaml
- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install ruff pytest
    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
```

</details>

- [ ] Lint with ruff
<summary>Example</summary>
<details>

```yaml
- name: Lint with ruff
  run: |
    # stop the build if there are Python syntax errors or undefined names
    ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
    # default set of ruff rules with GitHub Annotations
    ruff --format=github --target-version=py37 .
```

</details>

- [ ] Run tests and generate coverage via pytest
<summary>Example</summary>
<details>

```yaml
- name: Test with pytest
  run: |
    pip install pytest pytest-cov
    pytest tests.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
```

</details>

Need to find an example for using PyInstaller to build the binaries, and we'll probably want to do this for multiple target OS.
