### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by sergioramos** [refstudio/refstudio#11]
On every Commit/PR:

<details>

<summary>Example</summary>

```yaml
name: Continuous Integration

on:
  push:
    branches:
      - master
      - main
  pull_request:
```

</details>

- [ ] Install dependencies and setup environment (with caches)

<details>

<summary>Example</summary>

```yml
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
        env:
          YARN_CHECKSUM_BEHAVIOR: update
          YARN_ENABLE_SCRIPTS: 0
```

</details>

- [ ] Lint commits

<details>

<summary>Example</summary>

```yml
  commitlint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
        with:
          fetch-depth: 0
      - name: Commit Lint
        uses: wagoid/commitlint-github-action@v5.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

</details>

- [ ] Eslint

<details>

<summary>Example</summary>

```yml
  eslint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: ESLint
        run: yarn run lint
```

</details>

- [ ] Make sure dependencies are in sync (only makes sense in a monorepo )

<details>

<summary>Example</summary>

```yaml
  constraints:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: Constraints
        run: yarn constraints
```

</details>

- [ ] Test (with coverage report)

<details>

<summary>Example</summary>

```yml
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 'lts/*'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Test
        run: yarn run test --testLocationInResults --ci --json --outputFile="coverage.json"
        # this is not working well
      - name: Download Coverage Artifact
        uses: actions/download-artifact@v3.0.2
        continue-on-error: true
        with:
          name: coverage
          path: base-coverage.json
      - name: Fallback coverage report
        run: |
          [ -e "base-coverage.json" ] || cp coverage.json base-coverage.json
      - name: Jest coverage report
        if: github.event_name == 'pull_request'
        uses: ArtiomTr/jest-coverage-report-action@v2.0-rc.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-file: coverage.json
          base-coverage-file: base-coverage.json
          skip-step: all
          annotations: none
          icons: ascii
      - name: Set base coverage report
        if: github.event_name != 'pull_request'
        run: cp coverage.json base-coverage.json
      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v3.1.2
        if: github.event_name != 'pull_request'
        with:
          name: coverage
          path: base-coverage.json
          retention-days: 90
```

</details>

- [ ] Release and build (https://tauri.app/v1/guides/distribution/sign-macos)

<details>

<summary>Example</summary>

```yaml
  release:
    needs: [eslint, commitlint, test, constraints]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Generate release token
      id: release_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.RELEASE_APP_ID }}
        private_key: ${{ secrets.RELEASE_PRIVATE_KEY }}
    - name: Get branch
      uses: rlespinasse/github-slug-action@4.0.0
    - name: Release
      uses: ridedott/release-me-action@v3.6.25
      if: ${{ env.GITHUB_REF_SLUG == 'master' }}
      env:
        GITHUB_TOKEN: ${{ steps.release_token.outputs.token }}
```

```yaml
name: Continuous Delivery

on:
  release:
    types: [created]

jobs:
  bundle-sources:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.5.1
      with:
        node-version: 'lts/*'
    - name: Install dependencies
      run: yarn install --immutable
    - name: Bundle
    - name: Upload artifacts
      uses: Shopify/upload-to-release@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: 
        path: 
        repo-token: ${{ secrets.GITHUB_TOKEN }}
```

</details>
